### ISSUE TITLE
CI/CD with github actions

### ISSUE THREAD

**Issue by armoha** [armoha/euddraft#136]
- [x] completely replace setup.py to pyproject.toml
  * https://packaging.python.org/en/latest/discussions/setup-py-deprecated/
  * https://packaging.python.org/en/latest/guides/modernize-setup-py-project/#modernize-setup-py-project
- [x] also distribute `sdist` (currently only `bdist_wheel`)
- [ ] eudplib supports multiple python versions (currently 3.11 only)
- [ ] uses `uv` for building eudplib wheels
- [ ] build euddraft
  - [ ] Linux
  - [ ] macOS
  - [x] Windows

## Python
See `https://github.com/pyca/cryptography/issues/11548`
- eudplib
- euddraft uses cx_freeze: See `https://github.com/marcelotduarte/cx_Freeze/issues/1410#issuecomment-1851323175`
```yaml
name: Build app

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build_exe:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    name: Build app on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          cache: 'pip'
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade cx_Freeze
          # if you have a requirements file
          # pip install -r requirements.txt

      - name: Freeze app
        run: |
          if [[ ${{ matrix.os }} == macos-* ]]; then
            python setup.py bdist_mac
          elif [[ ${{ matrix.os }} == windows-* ]]; then
            python setup.py bdist_msi
          else
            # python setup.py bdist_appimage
            python setup.py build
          fi
          

      - name: Upload executable
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: app-${{ matrix.os }}
          path: build/**
          if-no-files-found: ignore
```

## C/C++: `CMake` (Linux) or Visual Studio solutions
For MSVC, github manages Windows Server 2022 host: https://github.com/actions/runner-images/blob/main/images/windows/Windows2022-Readme.md
- [StormLib](https://github.com/ladislav-zezula/StormLib): has binary releases for Windows

## C/C++: `CMake` & `pybind11`
See https://pybind11.readthedocs.io/en/stable/compiling.html
- freeze mpqprt
- libepScript.dll

## Rust: `pyo3`
- eudplib extensions

## Upload and download artifacts
https://github.com/dawidd6/action-download-artifact
공식 액션 `actions/download-artifact`은 다른 워크플로에서 업로드한 파일을 다운 받는게 안 된다.
`dawidd6/action-download-artifact` 을 사용해야 build와 publish를 분리할 수 있다.
```yaml
      - uses: dawidd6/action-download-artifact@bf251b5aa9c2f7eeb574a96ee720e24f801b7c11 # v6
        with:
    # Optional, a directory where to extract artifact(s), defaults to the current directory
          path: dist/
    # Optional, will use specified workflow run
    # use ${{ github.event.workflow_run.id }} when your action runs in a workflow_run event
    # and wants to download from the triggering workflow run
          run_id: ${{ github.event.inputs.run_id || github.event.workflow_run.id }}
```
